// Generated by Forge01 v1.5 hardware backend
// Deterministic RTL/structural HDL; external EDA is required for FPGA/ASIC use.

module tt_um_forge01_forgecpu_tt1(
    ui_in,
    uo_out,
    uio_in,
    uio_out,
    uio_oe,
    ena,
    clk,
    rst_n
);

    input [7:0] ui_in;
    output reg [7:0] uo_out = 0;
    input [7:0] uio_in;
    output [7:0] uio_out;
    output [7:0] uio_oe;
    input ena;
    input clk;
    input rst_n;
    reg [2:0] pc = 0;
    reg [7:0] acc = 0;
    reg halted = 0;
    reg [7:0] regs [0:3];
    reg [7:0] prog [0:7];
    reg [7:0] alu_out = 0;
    localparam MODE_LOAD = 0;
    localparam MODE_RUN = 1;
    localparam MODE_INSPECT = 2;
    localparam MODE_HOLD = 3;
    localparam OP_NOP = 0;
    localparam OP_LDI = 1;
    localparam OP_ADDI = 2;
    localparam OP_SUBI = 3;
    localparam OP_XORI = 4;
    localparam OP_ANDI = 5;
    localparam OP_ORI = 6;
    localparam OP_STORE = 7;
    localparam OP_LOAD = 8;
    localparam OP_JMP = 9;
    localparam OP_JZ = 10;
    localparam OP_INC = 11;
    localparam OP_DEC = 12;
    localparam OP_SHL = 13;
    localparam OP_SHR = 14;
    localparam OP_HALT = 15;
    wire [1:0] mode;
    assign mode = ui_in[7:6];
    wire [2:0] host_addr;
    assign host_addr = ui_in[2:0];
    wire [1:0] inspect_sel;
    assign inspect_sel = ui_in[1:0];
    wire [1:0] inspect_reg;
    assign inspect_reg = ui_in[3:2];
    wire [7:0] instr;
    wire [3:0] opcode;
    assign opcode = instr[7:4];
    wire [3:0] arg;
    assign arg = instr[3:0];
    wire [1:0] regsel;
    assign regsel = instr[1:0];

    assign instr = prog[pc];
    assign uio_out = 0;
    assign uio_oe = 0;

    always @* begin
        alu_out = acc;
        case (opcode)
            OP_LDI: alu_out = arg;
            OP_ADDI: alu_out = acc + arg;
            OP_SUBI: alu_out = acc - arg;
            OP_XORI: alu_out = acc ^ arg;
            OP_ANDI: alu_out = acc & arg;
            OP_ORI: alu_out = acc | arg;
            OP_LOAD: alu_out = regs[regsel];
            OP_INC: alu_out = acc + 1;
            OP_DEC: alu_out = acc - 1;
            OP_SHL: alu_out = acc << 1;
            OP_SHR: alu_out = acc >> 1;
            default: alu_out = acc;
        endcase
    end

    always @* begin
        uo_out = acc;
        case (mode)
            MODE_INSPECT: begin
                case (inspect_sel)
                    0: uo_out = acc;
                    1: uo_out = pc;
                    2: uo_out = regs[inspect_reg];
                    3: uo_out = halted;
                endcase
            end
            default: uo_out = acc;
        endcase
    end

    always @(posedge clk) begin
        if (rst_n == 0) begin
            pc <= 0;
            acc <= 0;
            halted <= 0;
        end else if (mode == MODE_LOAD && ena == 1) begin
            prog[host_addr] <= uio_in;
        end else if (mode == MODE_RUN && ena == 1 && halted == 0 && opcode == OP_HALT) begin
            halted <= 1;
        end else if (mode == MODE_RUN && ena == 1 && halted == 0 && opcode == OP_JMP) begin
            pc <= arg[2:0];
        end else if (mode == MODE_RUN && ena == 1 && halted == 0 && opcode == OP_JZ && acc == 0) begin
            pc <= arg[2:0];
        end else if (mode == MODE_RUN && ena == 1 && halted == 0 && opcode == OP_STORE) begin
            regs[regsel] <= acc;
            pc <= pc + 1;
        end else if (mode == MODE_RUN && ena == 1 && halted == 0) begin
            acc <= alu_out;
            pc <= pc + 1;
        end else begin
            halted <= halted;
        end
    end
endmodule
